repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [ python ]
        files: ^app/.*\.py$
      - id: ruff
        name: ruff
        entry: ruff check
        language: system
        types: [ python ]
        files: ^app/.*\.py$